//! The generated docs: `docs/config.md`, every key with its default, when a change
//! applies and its description, and `docs/config.schema.json`, the JSON schema.
//! `cargo xtask config-docs` writes both, and CI fails when they are not current.

use std::fmt::Write as _;

use serde_json::Value as Json;

use crate::effective::{lookup, show};
use crate::keys::{Applies, description, json_schema, keys};
use crate::{ConfigError, Settings};

/// The text of `docs/config.md`.
pub fn reference() -> Result<String, ConfigError> {
    let defaults = toml_edit::ser::to_document(&Settings::default())
        .map_err(|source| ConfigError::Encode { source })?;
    let schema = json_schema();
    let mut out = String::from(INTRO);
    let mut table: Option<String> = None;
    let mut first = true;
    for key in keys() {
        let (heading, name) = match key.split_once('.') {
            Some((table, name)) => (Some(table.to_owned()), name),
            None => (None, key.as_str()),
        };
        if first || heading != table {
            let title =
                heading.as_deref().map_or_else(|| "Top level".to_owned(), |t| format!("[{t}]"));
            let _ = write!(out, "\n## {title}\n\n");
            if let Some(text) = heading.as_deref().and_then(|t| table_description(&schema, t)) {
                let _ = write!(out, "{}\n\n", one_line(&text));
            }
            out.push_str("| Key | Default | Applies | Description |\n|---|---|---|---|\n");
            table = heading;
            first = false;
        }
        let default = match lookup(&defaults, &key).map(show) {
            None => "unset".to_owned(),
            Some(text) if text.starts_with('<') => "built in".to_owned(),
            Some(text) => format!("`{text}`"),
        };
        let text = description(&key).map(|text| one_line(&text)).unwrap_or_default();
        let _ = writeln!(
            out,
            "| `{name}` | {} | {} | {} |",
            cell(&default),
            Applies::of(&key).as_str(),
            cell(&text)
        );
    }
    Ok(out)
}

/// The text of `docs/config.schema.json`.
pub fn schema_text() -> String {
    // A JSON value always serializes.
    let mut text = serde_json::to_string_pretty(&json_schema()).unwrap_or_default();
    text.push('\n');
    text
}

const INTRO: &str = "\
# config.toml

<!-- Generated by `cargo xtask config-docs` from efr-config. Do not edit by hand. -->

`config.toml` is the one config file of `efrd` and `efr`. It lives in the config root:
`$EFR_CONFIG_DIR`, else `$EFR_HOME/config`, else `$XDG_CONFIG_HOME/efr` (`efr paths`
shows which). The file is optional: a missing file is an empty one, and every key is
optional. An unknown key is an error. The file holds no secrets, so it can live in a
dotfiles repository behind a symbolic link.

`efr config edit` opens it (and creates it from the commented example), `efr config
check` checks it, and `efr config set` and `efr config unset` change one key and keep
the comments. `docs/config.schema.json` is its JSON schema; the `#:schema` line at the
top of the example file points editors to it.

The daemon reloads the file when it changes, on `efr config reload` and on `SIGHUP`
(`systemctl --user reload efrd`). A file with an error keeps the old settings, and
`efr status` shows the error. The Applies column says when a change takes effect:

- `live`: the daemon applies it without a restart, from the next turn, prompt, tool
  call or new hidden shell. A running turn keeps the settings it started with.
- `restart`: the daemon keeps the old value until `efrd` restarts, and
  `efr config show` lists the key as needing a restart.
- `client`: only `efr` reads it, each time it runs.
";

/// The description of the table `name`, from the field that holds it.
fn table_description(schema: &Json, name: &str) -> Option<String> {
    let text = schema.get("properties")?.get(name)?.get("description")?.as_str()?;
    Some(text.to_owned())
}

/// `text` on one line: a doc comment's line breaks become spaces.
fn one_line(text: &str) -> String {
    text.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// `text` safe inside a Markdown table cell.
fn cell(text: &str) -> String {
    text.replace('|', "\\|")
}

#[cfg(test)]
mod tests;
