//! The live-state preamble: what the model knows about the user's shell this turn.
//!
//! It is regenerated by the daemon on every turn from the prompt's `ShellContext`, the
//! last command that `prompt.send` carried in memory, the scope derivation and the
//! machine facts, and it rides as the first block of the newest prompt only. Earlier
//! prompts go back to the model without it, so the history stays the same from turn
//! to turn and the model never mistakes an old directory for the current one. The
//! static rules live apart from it, in the system prompt.

use std::fmt::{self, Write as _};
use std::path::PathBuf;

use efr_scope::Repo;

/// The longest last command shown, in characters; a longer one is cut with a marker.
const COMMAND_MAX_CHARS: usize = 400;

/// The state of the user's shell and machine for one turn.
///
/// `Debug` leaves out the last command, which can hold a secret such as
/// `export TOKEN=...`.
#[derive(Clone, PartialEq, Eq)]
pub(crate) struct LiveState {
    /// The user's working directory.
    pub(crate) cwd: PathBuf,
    /// The user's previous directory, `$OLDPWD`.
    pub(crate) oldpwd: Option<PathBuf>,
    /// The last command line from the user's history.
    pub(crate) last_command: Option<String>,
    /// The exit status of the last command, `$?`.
    pub(crate) last_status: Option<i32>,
    /// The git work tree around the working directory.
    pub(crate) repo: Option<Repo>,
    /// The user's home directory.
    pub(crate) home: PathBuf,
    /// The host name.
    pub(crate) host: Option<String>,
    /// The operating system and distribution, such as `Arch Linux`.
    pub(crate) os: Option<String>,
    /// True when the user's shell runs over SSH.
    pub(crate) ssh: bool,
    /// The conversation's `$SCRATCH`.
    pub(crate) scratch: PathBuf,
    /// Where the conversation's hidden shell last reported to be, when it differs from
    /// the user's directory.
    pub(crate) agent_cwd: Option<PathBuf>,
}

impl fmt::Debug for LiveState {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // NOTE: last_command is deliberately missing; see the type's doc comment.
        f.debug_struct("LiveState")
            .field("cwd", &self.cwd)
            .field("oldpwd", &self.oldpwd)
            .field("last_status", &self.last_status)
            .field("repo", &self.repo)
            .field("home", &self.home)
            .field("host", &self.host)
            .field("os", &self.os)
            .field("ssh", &self.ssh)
            .field("scratch", &self.scratch)
            .field("agent_cwd", &self.agent_cwd)
            .finish_non_exhaustive()
    }
}

impl LiveState {
    /// The preamble text: one fact per line inside a `<live_state>` block, so the model
    /// can tell it from the user's words.
    pub(crate) fn render(&self) -> String {
        let mut text = String::from("<live_state>\n");
        // NOTE: writing to a String cannot fail, so the results are ignored.
        let _ = write!(text, "The user's shell is in {}", self.cwd.display());
        match &self.oldpwd {
            Some(oldpwd) => {
                let _ = writeln!(text, "; the previous directory was {}.", oldpwd.display());
            }
            None => text.push_str(".\n"),
        }
        text.push_str(
            "Commands you run with the shell tool start there in a new hidden shell; \
             the hidden shell keeps its own directory between calls.\n",
        );
        if let Some(agent_cwd) = self.agent_cwd.as_ref().filter(|dir| **dir != self.cwd) {
            let _ = writeln!(text, "Your hidden shell is in {}.", agent_cwd.display());
        }
        if let Some(command) = &self.last_command {
            text.push_str(&last_command(command, self.last_status));
        } else if let Some(status) = self.last_status {
            let _ = writeln!(text, "The user's last command exited with status {status}.");
        }
        if let Some(repo) = &self.repo {
            let _ = write!(text, "Git work tree: {}", repo.root.display());
            match &repo.branch {
                Some(branch) => {
                    let _ = writeln!(text, ", branch {branch}.");
                }
                None => text.push_str(", detached HEAD.\n"),
            }
        }
        let _ = writeln!(text, "Home: {}", self.home.display());
        match (&self.host, &self.os) {
            (Some(host), Some(os)) => {
                let _ = writeln!(text, "Host: {host} ({os})");
            }
            (Some(host), None) => {
                let _ = writeln!(text, "Host: {host}");
            }
            (None, Some(os)) => {
                let _ = writeln!(text, "OS: {os}");
            }
            (None, None) => {}
        }
        if self.ssh {
            text.push_str("The user's shell runs over SSH.\n");
        }
        let _ = writeln!(
            text,
            "$SCRATCH: {} (your own directory for files; writing there needs no approval)",
            self.scratch.display()
        );
        text.push_str("</live_state>");
        text
    }
}

/// The line or block that shows the last command and its status.
fn last_command(command: &str, status: Option<i32>) -> String {
    let command = cut(command.trim_end());
    if command.contains('\n') || command.contains('`') {
        let status = match status {
            Some(status) => format!(", which exited with status {status}"),
            None => String::new(),
        };
        format!("The user's last command{status}:\n```\n{command}\n```\n")
    } else {
        let status = match status {
            Some(status) => format!("; it exited with status {status}"),
            None => String::new(),
        };
        format!("The user's last command was `{command}`{status}.\n")
    }
}

/// `text` cut to [`COMMAND_MAX_CHARS`] characters, with a marker when cut.
fn cut(text: &str) -> String {
    match text.char_indices().nth(COMMAND_MAX_CHARS) {
        Some((at, _)) => format!("{} [cut]", &text[..at]),
        None => text.to_owned(),
    }
}

#[cfg(test)]
mod tests;
